/*
 * Waveshare ESP32-P4-WIFI6-POE-ETH pin map (board wiki + schematic; cross-checked
 * against the espp BSP for the same board).
 */
#pragma once

/* Ethernet: internal EMAC, RMII, IP101GRI PHY. REF_CLK is generated by the PHY
 * (25 MHz crystal) and fed INTO the P4 on GPIO50. */
#define BOARD_ETH_PHY_ADDR      1
#define BOARD_ETH_PHY_RST_GPIO  51
#define BOARD_ETH_MDC_GPIO      31
#define BOARD_ETH_MDIO_GPIO     52
#define BOARD_ETH_REFCLK_GPIO   50
#define BOARD_ETH_TX_EN_GPIO    49
#define BOARD_ETH_TXD0_GPIO     34
#define BOARD_ETH_TXD1_GPIO     35   /* shared with the BOOT strap */
#define BOARD_ETH_CRS_DV_GPIO   28
#define BOARD_ETH_RXD0_GPIO     29
#define BOARD_ETH_RXD1_GPIO     30

/* ESP32-C6 (Wi-Fi 6) over SDIO slot 1 — configured through esp_hosted Kconfig
 * (sdkconfig.defaults): CLK 18, CMD 19, D0..D3 14..17, reset 54. */

/* USB-A: USB 2.0 OTG High-Speed, host role. VBUS is always on (no enable GPIO). */

/* microSD (unused by this firmware): CLK 43 CMD 44 D0..D3 39..42 */

/* Internal I2C (unused): SDA 7, SCL 8 */

#define BOARD_HOSTNAME_DEFAULT  "rrcloud-ingest"
