"""Rust emitter: a standalone crate `rrcloud-proto` (serde types, validated newtypes, maps, keys, codecs)."""
from __future__ import annotations

from pathlib import Path

from model import Model, Record, Field, TypeRef, snake

HEADER = "// @generated by protocol/rrcgen from protocol/rrcloud.protocol.toml — DO NOT EDIT.\n"

RUST_PRIM = {"u8": "u8", "u32": "u32", "u64": "u64", "i64": "i64", "usize": "usize", "bool": "bool", "string": "String"}


def rust_type(m: Model, t: TypeRef) -> str:
    if t.is_primitive:
        base = RUST_PRIM[t.name]
    else:
        kind = m.kind_of(t.name)
        if kind == "scalar" and m.scalars[t.name].kind != "string":
            base = {"i64": "i64", "u64": "u64"}[m.scalars[t.name].kind]
        else:
            base = t.name
    return f"Vec<{base}>" if t.array else base


def rust_literal(m: Model, t: TypeRef, v) -> str:
    if t.array:
        inner = ", ".join(rust_literal(m, TypeRef(t.name), x) for x in v)
        return f"vec![{inner}]"
    if t.name == "string":
        return f"{v!r}.to_string()".replace("'", '"')
    if t.name == "bool":
        return "true" if v else "false"
    return str(v)


def doc(text: str, indent: str = "") -> str:
    if not text:
        return ""
    return "".join(f"{indent}/// {line}\n" for line in text.splitlines())


def emit(m: Model, out_dir: Path) -> None:
    crate = out_dir / "rust" / "rrcloud-proto"
    (crate / "src").mkdir(parents=True, exist_ok=True)
    (crate / "Cargo.toml").write_text(CARGO_TOML, encoding="utf-8")
    (crate / "src" / "lib.rs").write_text(lib_rs(m), encoding="utf-8")


CARGO_TOML = """# @generated by protocol/rrcgen — DO NOT EDIT (edit protocol/rrcloud.protocol.toml and regenerate).
[package]
name = "rrcloud-proto"
version = "0.1.0"
edition = "2021"
description = "RapidRawCloud sync protocol wire types, keys and codecs (generated)"
license = "AGPL-3.0-only"
publish = false

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
unicode-normalization = "0.1"
blake3 = "1"
flate2 = "1"
"""


def lib_rs(m: Model) -> str:
    o: list[str] = [HEADER]
    o.append(f'//! {m.protocol["description"]} — protocol definition v{m.protocol["idl_version"]}, wire version {m.protocol["wire_version"]}.\n')
    o.append("//!\n//! Generated from `protocol/rrcloud.protocol.toml`. See `protocol/gen/PROTOCOL.md`.\n\n")
    o.append("#![allow(clippy::all)]\n#![forbid(unsafe_code)]\n\n")
    o.append("use std::collections::BTreeMap;\nuse std::fmt;\nuse std::io::{Read as _, Write as _};\n\nuse serde::{Deserialize, Serialize};\n\n")

    # ---- constants
    o.append("// ---------------------------------------------------------------- constants\n\n")
    for c in m.constants.values():
        o.append(doc(c.doc))
        if c.type == "str":
            o.append(f'pub const {c.name}: &str = "{c.value}";\n\n')
        elif c.type.startswith("["):
            inner = c.type[1:-1]
            o.append(f"pub const {c.name}: &[{inner}] = &[{', '.join(str(v) for v in c.value)}];\n\n")
        else:
            o.append(f"pub const {c.name}: {c.type} = {c.value};\n\n")

    # ---- errors
    o.append(ERROR_RS)

    # ---- scalars
    o.append("// ---------------------------------------------------------------- scalars\n\n")
    o.append(VALIDATORS_RS)
    for s in m.scalars.values():
        if s.kind != "string":
            o.append(doc(s.doc))
            o.append(f"pub type {s.name} = {s.kind};\n\n")
            continue
        o.append(doc(s.doc))
        o.append("#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]\n")
        o.append('#[serde(try_from = "String", into = "String")]\n')
        o.append(f"pub struct {s.name}(String);\n\n")
        o.append(f"impl {s.name} {{\n")
        o.append(f"    /// Validates `s` ({s.format}) without rewriting it (the strict wire lane).\n")
        o.append(f"    pub fn new(s: impl Into<String>) -> Result<Self, ProtoError> {{\n        let s = s.into();\n")
        o.append(f"        validate_scalar(\"{s.name}\", &s, {s.buf_len}, ScalarFormat::{fmt_variant(s.format)}, {s.length if s.length is not None else 0})?;\n")
        o.append("        Ok(Self(s))\n    }\n")
        if s.format == "relkey":
            o.append("    /// The local path-mapping lane: NFC-normalizes first, then validates (keys.rs RelKey::new).\n")
            o.append("    pub fn normalize(s: impl Into<String>) -> Result<Self, ProtoError> {\n        use unicode_normalization::UnicodeNormalization;\n")
            o.append("        let s: String = s.into().nfc().collect();\n        Self::new(s)\n    }\n")
        o.append("    pub fn as_str(&self) -> &str {\n        &self.0\n    }\n}\n\n")
        o.append(f"impl TryFrom<String> for {s.name} {{\n    type Error = ProtoError;\n    fn try_from(s: String) -> Result<Self, ProtoError> {{\n        Self::new(s)\n    }}\n}}\n")
        o.append(f"impl From<{s.name}> for String {{\n    fn from(v: {s.name}) -> String {{\n        v.0\n    }}\n}}\n")
        o.append(f"impl AsRef<str> for {s.name} {{\n    fn as_ref(&self) -> &str {{\n        &self.0\n    }}\n}}\n")
        o.append(f"impl fmt::Display for {s.name} {{\n    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {{\n        f.write_str(&self.0)\n    }}\n}}\n\n")

    # ---- enums
    o.append("// ---------------------------------------------------------------- enums\n\n")
    for e in m.enums.values():
        o.append(doc(e.doc))
        o.append("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord, Serialize, Deserialize)]\n")
        o.append(f"pub enum {e.name} {{\n")
        for v in e.values:
            o.append(doc(v.doc, "    "))
            o.append(f'    #[serde(rename = "{v.wire}")]\n    {v.name},\n')
        o.append("}\n\n")
        o.append(f"impl {e.name} {{\n    pub const ALL: &'static [{e.name}] = &[{', '.join(f'{e.name}::{v.name}' for v in e.values)}];\n")
        o.append("    /// The wire spelling.\n    pub fn as_wire(self) -> &'static str {\n        match self {\n")
        for v in e.values:
            o.append(f'            {e.name}::{v.name} => "{v.wire}",\n')
        o.append("        }\n    }\n")
        o.append("    pub fn from_wire(s: &str) -> Option<Self> {\n        match s {\n")
        for v in e.values:
            o.append(f'            "{v.wire}" => Some({e.name}::{v.name}),\n')
        o.append("            _ => None,\n        }\n    }\n}\n\n")
        o.append(f"impl fmt::Display for {e.name} {{\n    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {{\n        f.write_str(self.as_wire())\n    }}\n}}\n\n")

    # ---- maps
    o.append("// ---------------------------------------------------------------- maps\n\n")
    for mp in m.maps.values():
        if not mp.drop_zero:
            o.append(doc(mp.doc))
            o.append(f"pub type {mp.name} = BTreeMap<{mp.key}, {mp.value}>;\n\n")
            continue
        o.append(doc(mp.doc))
        o.append("#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize, Deserialize)]\n")
        o.append(f'#[serde(from = "BTreeMap<{mp.key}, {mp.value}>", into = "BTreeMap<{mp.key}, {mp.value}>")]\n')
        o.append(f"pub struct {mp.name}(BTreeMap<{mp.key}, {mp.value}>);\n\n")
        o.append(f"impl {mp.name} {{\n    pub fn new() -> Self {{\n        Self::default()\n    }}\n")
        o.append(f"    /// Missing components read as 0.\n    pub fn get(&self, k: &{mp.key}) -> {mp.value} {{\n        self.0.get(k).copied().unwrap_or(0)\n    }}\n")
        o.append(f"    /// Sets a component; a zero removes it (zero components are never stored).\n    pub fn set(&mut self, k: {mp.key}, v: {mp.value}) {{\n        if v == 0 {{\n            self.0.remove(&k);\n        }} else {{\n            self.0.insert(k, v);\n        }}\n    }}\n")
        o.append(f"    /// Increments a component (saturating).\n    pub fn bump(&mut self, k: &{mp.key}) {{\n        let slot = self.0.entry(k.clone()).or_insert(0);\n        *slot = slot.saturating_add(1);\n    }}\n")
        o.append("    /// Element-wise maximum.\n    pub fn merge(&mut self, other: &Self) {\n        for (k, &v) in &other.0 {\n            if v == 0 {\n                continue;\n            }\n            let slot = self.0.entry(k.clone()).or_insert(0);\n            *slot = (*slot).max(v);\n        }\n    }\n")
        o.append(f"    pub fn iter(&self) -> std::collections::btree_map::Iter<'_, {mp.key}, {mp.value}> {{\n        self.0.iter()\n    }}\n")
        o.append("    pub fn len(&self) -> usize {\n        self.0.len()\n    }\n    pub fn is_empty(&self) -> bool {\n        self.0.is_empty()\n    }\n")
        o.append(f"    /// Ordering of two vectors: Equal, Greater (self dominates), Less, or Concurrent (§2.6).\n    pub fn compare(&self, other: &Self) -> VvOrder {{\n        let mut ge = true;\n        let mut le = true;\n        for k in self.0.keys().chain(other.0.keys()) {{\n            let a = self.get(k);\n            let b = other.get(k);\n            if a < b {{\n                ge = false;\n            }}\n            if a > b {{\n                le = false;\n            }}\n        }}\n        match (ge, le) {{\n            (true, true) => VvOrder::Equal,\n            (true, false) => VvOrder::Greater,\n            (false, true) => VvOrder::Less,\n            (false, false) => VvOrder::Concurrent,\n        }}\n    }}\n}}\n\n")
        o.append(f"impl From<BTreeMap<{mp.key}, {mp.value}>> for {mp.name} {{\n    fn from(map: BTreeMap<{mp.key}, {mp.value}>) -> Self {{\n        map.into_iter().collect()\n    }}\n}}\n")
        o.append(f"impl From<{mp.name}> for BTreeMap<{mp.key}, {mp.value}> {{\n    fn from(v: {mp.name}) -> Self {{\n        v.0\n    }}\n}}\n")
        o.append(f"impl FromIterator<({mp.key}, {mp.value})> for {mp.name} {{\n    fn from_iter<T: IntoIterator<Item = ({mp.key}, {mp.value})>>(iter: T) -> Self {{\n        let mut map = BTreeMap::new();\n        for (k, v) in iter {{\n            if v == 0 {{\n                continue;\n            }}\n            let slot = map.entry(k).or_insert(0);\n            *slot = (*slot).max(v);\n        }}\n        Self(map)\n    }}\n}}\n\n")
    o.append("/// Result of comparing two version vectors (§2.6).\n#[derive(Debug, Clone, Copy, PartialEq, Eq)]\npub enum VvOrder {\n    Equal,\n    Greater,\n    Less,\n    Concurrent,\n}\n\n")

    # ---- records
    o.append("// ---------------------------------------------------------------- records\n\n")
    for r in m.records.values():
        o.append(record_rs(m, r))

    # ---- keys
    o.append("// ---------------------------------------------------------------- bucket keys\n\n")
    o.append("fn blake3_32(s: &str) -> String {\n    blake3::hash(s.as_bytes()).to_hex()[..32].to_string()\n}\n\n")
    for k in m.keys.values():
        o.append(key_rs(m, k))

    # ---- documents
    o.append(documents_rs(m))
    return "".join(o)


def fmt_variant(fmt: str) -> str:
    return {"uuid4-lower": "Uuid4Lower", "relkey": "RelKey", "lower-hex": "LowerHex", "any": "Any"}[fmt]


ERROR_RS = """// ---------------------------------------------------------------- errors

/// Decode/validation failure. Fail-closed by design (§2.2 min-reader rule).
#[derive(Debug, thiserror::Error)]
pub enum ProtoError {
    #[error("invalid {ty}: {reason}: {value:?}")]
    Invalid {
        ty: &'static str,
        reason: &'static str,
        value: String,
    },
    #[error("unsupported format version {version}")]
    UnsupportedVersion { version: u64 },
    #[error("document has no version field")]
    MissingVersion,
    #[error("version field is not an unsigned integer: {value}")]
    MalformedVersion { value: String },
    #[error("invalid JSON: {0}")]
    Json(#[from] serde_json::Error),
    #[error("segment has {count} entries, cap is {cap}")]
    TooManyEntries { count: usize, cap: usize },
    #[error("encoded document is {size} bytes, cap is {cap}")]
    TooLarge { size: usize, cap: usize },
    #[error("gzip: {0}")]
    Gzip(#[from] std::io::Error),
    #[error("manifest line {line}: {reason}")]
    ManifestLine { line: usize, reason: String },
}

"""

VALIDATORS_RS = """#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ScalarFormat {
    Uuid4Lower,
    RelKey,
    LowerHex,
    Any,
}

pub fn is_lower_hex(s: &str, len: usize) -> bool {
    s.len() == len && s.bytes().all(|b| b.is_ascii_digit() || (b'a'..=b'f').contains(&b))
}

pub fn is_uuid4_lower(s: &str) -> bool {
    let b = s.as_bytes();
    if b.len() != 36 {
        return false;
    }
    for (i, &c) in b.iter().enumerate() {
        match i {
            8 | 13 | 18 | 23 => {
                if c != b'-' {
                    return false;
                }
            }
            14 => {
                if c != b'4' {
                    return false;
                }
            }
            19 => {
                if !matches!(c, b'8' | b'9' | b'a' | b'b') {
                    return false;
                }
            }
            _ => {
                if !(c.is_ascii_digit() || (b'a'..=b'f').contains(&c)) {
                    return false;
                }
            }
        }
    }
    true
}

fn is_windows_reserved(seg: &str) -> bool {
    let base = seg.split('.').next().unwrap_or(seg).trim_end_matches(' ');
    let bytes = base.as_bytes();
    if bytes.len() == 3 {
        return [&b"con"[..], b"prn", b"aux", b"nul"].iter().any(|r| bytes.eq_ignore_ascii_case(r));
    }
    if bytes.len() > 3 && (bytes[..3].eq_ignore_ascii_case(b"com") || bytes[..3].eq_ignore_ascii_case(b"lpt")) {
        let mut rest = base[3..].chars();
        if let (Some(c), None) = (rest.next(), rest.next()) {
            return matches!(c, '1'..='9' | '\\u{b9}' | '\\u{b2}' | '\\u{b3}');
        }
    }
    false
}

/// The §1.1 relkey rule set on already-NFC input (the strict wire lane).
pub fn validate_relkey(s: &str) -> Result<(), &'static str> {
    if s.is_empty() {
        return Err("empty");
    }
    if s.contains('\\\\') {
        return Err("backslash");
    }
    if s.contains(':') {
        return Err("colon");
    }
    if s.chars().any(|c| c.is_control()) {
        return Err("control character");
    }
    if !unicode_normalization::is_nfc(s) {
        return Err("not NFC");
    }
    if s.starts_with('/') {
        return Err("leading slash");
    }
    for seg in s.split('/') {
        if seg.is_empty() || seg == "." || seg == ".." {
            return Err("dot, dot-dot, or empty segment");
        }
        if seg.ends_with('.') || seg.ends_with(' ') {
            return Err("segment ends with dot or space");
        }
        if seg.starts_with(ENGINE_TEMP_PREFIX) {
            return Err("engine-reserved `.rr.` segment");
        }
        if is_windows_reserved(seg) {
            return Err("Windows-reserved device name");
        }
    }
    Ok(())
}

fn validate_scalar(ty: &'static str, s: &str, max_len: usize, fmt: ScalarFormat, exact_len: usize) -> Result<(), ProtoError> {
    let fail = |reason: &'static str| ProtoError::Invalid { ty, reason, value: s.to_string() };
    if s.len() > max_len {
        return Err(fail("too long"));
    }
    match fmt {
        ScalarFormat::Uuid4Lower => {
            if !is_uuid4_lower(s) {
                return Err(fail("not a canonical lowercase UUIDv4"));
            }
        }
        ScalarFormat::LowerHex => {
            if !is_lower_hex(s, exact_len) {
                return Err(fail("not lowercase hex of the required length"));
            }
        }
        ScalarFormat::RelKey => validate_relkey(s).map_err(fail)?,
        ScalarFormat::Any => {}
    }
    Ok(())
}

"""


def record_rs(m: Model, r: Record) -> str:
    o: list[str] = [doc(r.doc)]
    o.append("#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]\n")
    if r.naming == "camel":
        o.append('#[serde(rename_all = "camelCase")]\n')
    o.append(f"pub struct {r.name} {{\n")
    defaults: list[str] = []
    for f in r.fields:
        o.append(doc(f.doc, "    "))
        ty = rust_type(m, f.type)
        if f.optional:
            o.append('    #[serde(default, skip_serializing_if = "Option::is_none")]\n')
            o.append(f"    pub {f.name}: Option<{ty}>,\n")
        elif f.has_default:
            fname = f"default_{snake(r.name)}_{f.name}"
            o.append(f'    #[serde(default = "{fname}")]\n')
            o.append(f"    pub {f.name}: {ty},\n")
            defaults.append(f"fn {fname}() -> {ty} {{\n    {rust_literal(m, f.type, f.default)}\n}}\n")
        else:
            o.append(f"    pub {f.name}: {ty},\n")
    o.append("}\n\n")
    o.extend(defaults)
    if defaults:
        o.append("\n")
    o.append(f"impl {r.name} {{\n")
    o.append("    /// Serializes as one JSON document (deterministic: fixed field order, omitted `None`s).\n")
    o.append("    pub fn to_json(&self) -> Result<String, ProtoError> {\n        Ok(serde_json::to_string(self)?)\n    }\n")
    if r.version_field:
        vers = ", ".join(str(v) for v in r.supported_versions)
        o.append(f"    /// Versions this reader accepts in `{r.version_field}`.\n    pub const SUPPORTED_VERSIONS: &'static [u64] = &[{vers}];\n")
        o.append("    /// Decodes with the min-reader gate: an unsupported version is a typed error, never skipped.\n")
        o.append("    pub fn from_json(s: &str) -> Result<Self, ProtoError> {\n        Self::from_json_slice(s.as_bytes())\n    }\n")
        o.append("    pub fn from_json_slice(bytes: &[u8]) -> Result<Self, ProtoError> {\n")
        o.append("        let value: serde_json::Value = serde_json::from_slice(bytes)?;\n")
        o.append(f'        let version = match value.get("{r.version_field}") {{\n')
        o.append("            None => return Err(ProtoError::MissingVersion),\n")
        o.append("            Some(v) => v.as_u64().ok_or_else(|| ProtoError::MalformedVersion { value: v.to_string() })?,\n        };\n")
        o.append("        if !Self::SUPPORTED_VERSIONS.contains(&version) {\n            return Err(ProtoError::UnsupportedVersion { version });\n        }\n")
        o.append("        Ok(serde_json::from_value(value)?)\n    }\n")
    else:
        o.append("    pub fn from_json(s: &str) -> Result<Self, ProtoError> {\n        Ok(serde_json::from_str(s)?)\n    }\n")
        o.append("    pub fn from_json_slice(bytes: &[u8]) -> Result<Self, ProtoError> {\n        Ok(serde_json::from_slice(bytes)?)\n    }\n")
    o.append("}\n\n")
    return "".join(o)


def key_rs(m: Model, k) -> str:
    args = []
    for pname, ptype in k.params.items():
        if ptype in m.scalars:
            s = m.scalars[ptype]
            args.append(f"{pname}: &{ptype}" if s.kind == "string" else f"{pname}: {ptype}")
        elif ptype in m.enums:
            args.append(f"{pname}: {ptype}")
        else:
            args.append(f"{pname}: &str")
    o = [doc(k.doc), f"/// `{k.template}`\n", f"pub fn key_{k.name}({', '.join(args)}) -> String {{\n    let mut s = String::new();\n"]
    for p in k.parts:
        if p.literal is not None:
            o.append(f"    s.push_str({p.literal!r});\n".replace("'", '"'))
        elif p.fmt == "hex16":
            o.append(f'    s.push_str(&format!("{{:016x}}", {p.param}));\n')
        elif p.fmt == "blake3_32":
            o.append(f"    s.push_str(&blake3_32({p.param}.as_str()));\n")
        else:
            ptype = k.params[p.param]
            if ptype in m.enums:
                o.append(f"    s.push_str({p.param}.as_wire());\n")
            elif ptype in m.scalars and m.scalars[ptype].kind == "string":
                o.append(f"    s.push_str({p.param}.as_str());\n")
            elif ptype in m.scalars:
                o.append(f"    s.push_str(&{p.param}.to_string());\n")
            else:
                o.append(f"    s.push_str({p.param});\n")
    o.append("    s\n}\n\n")
    return "".join(o)


def documents_rs(m: Model) -> str:
    o: list[str] = ["// ---------------------------------------------------------------- documents\n\n"]
    for d in m.documents.values():
        enc = d.data.get("encoding")
        if enc == "ndjson":
            rec = d.data["record"]
            lim_e = next((l for l in d.data.get("limits", []) if "ENTRIES" in l), None)
            lim_b = next((l for l in d.data.get("limits", []) if "BYTES" in l), None)
            o.append(f"/// Encodes a `{d.name}` document: one `{rec}` JSON line per entry, newline-terminated.\n")
            o.append(f"pub fn encode_{d.name}(entries: &[{rec}]) -> Result<Vec<u8>, ProtoError> {{\n")
            if lim_e:
                o.append(f"    if entries.len() > {lim_e} {{\n        return Err(ProtoError::TooManyEntries {{ count: entries.len(), cap: {lim_e} }});\n    }}\n")
            o.append("    let mut out = Vec::new();\n    for e in entries {\n        out.extend_from_slice(e.to_json()?.as_bytes());\n        out.push(b'\\n');\n    }\n")
            if lim_b:
                o.append(f"    if out.len() > {lim_b} {{\n        return Err(ProtoError::TooLarge {{ size: out.len(), cap: {lim_b} }});\n    }}\n")
            o.append("    Ok(out)\n}\n\n")
            o.append(f"/// Decodes a `{d.name}` document fail-closed: the first unreadable line aborts the whole decode.\n")
            o.append(f"pub fn decode_{d.name}(bytes: &[u8]) -> Result<Vec<{rec}>, ProtoError> {{\n")
            if lim_b:
                o.append(f"    if bytes.len() > {lim_b} {{\n        return Err(ProtoError::TooLarge {{ size: bytes.len(), cap: {lim_b} }});\n    }}\n")
            o.append("    let mut out = Vec::new();\n    for line in bytes.split(|&b| b == b'\\n') {\n        if line.is_empty() {\n            continue;\n        }\n")
            if lim_e:
                o.append(f"        if out.len() == {lim_e} {{\n            return Err(ProtoError::TooManyEntries {{ count: out.len() + 1, cap: {lim_e} }});\n        }}\n")
            o.append(f"        out.push({rec}::from_json_slice(line)?);\n    }}\n    Ok(out)\n}}\n\n")
        elif enc == "gzip-ndjson":
            hdr = d.data["header"]
            rows = d.data["rows"]
            name = d.name.capitalize()
            lim_fetch = next((l for l in d.data.get("limits", []) if "FETCH" in l), None)
            lim_dec = next((l for l in d.data.get("limits", []) if "DECODED" in l), None)
            o.append(f"/// A decoded `{d.name}` document: header line, then rows.\n#[derive(Debug, Clone, PartialEq, Eq, Default)]\npub struct {name} {{\n    pub header: Option<{hdr}>,\n")
            for rr in rows:
                o.append(f"    pub {snake(rr)}s: Vec<{rr}>,\n")
            o.append("}\n\n")
            o.append(f"/// gzip NDJSON: header, then rows in declaration order. Deterministic for the same input.\n")
            o.append(f"pub fn encode_{d.name}(doc: &{name}) -> Result<Vec<u8>, ProtoError> {{\n    let mut nd = Vec::new();\n")
            o.append("    if let Some(h) = &doc.header {\n        nd.extend_from_slice(h.to_json()?.as_bytes());\n        nd.push(b'\\n');\n    }\n")
            for rr in rows:
                o.append(f"    for r in &doc.{snake(rr)}s {{\n        nd.extend_from_slice(r.to_json()?.as_bytes());\n        nd.push(b'\\n');\n    }}\n")
            o.append("    let mut enc = flate2::write::GzEncoder::new(Vec::new(), flate2::Compression::default());\n    enc.write_all(&nd)?;\n    Ok(enc.finish()?)\n}\n\n")
            o.append(f"/// Inflates (multi-member aware) and decodes fail-closed; row kind is chosen by which row record's first field is present.\n")
            o.append(f"pub fn decode_{d.name}(bytes: &[u8]) -> Result<{name}, ProtoError> {{\n")
            if lim_fetch:
                o.append(f"    if bytes.len() > {lim_fetch} {{\n        return Err(ProtoError::TooLarge {{ size: bytes.len(), cap: {lim_fetch} }});\n    }}\n")
            o.append("    let mut nd = Vec::new();\n    let mut dec = flate2::read::MultiGzDecoder::new(bytes);\n")
            if lim_dec:
                o.append(f"    dec.by_ref().take({lim_dec} as u64 + 1).read_to_end(&mut nd)?;\n    if nd.len() > {lim_dec} {{\n        return Err(ProtoError::TooLarge {{ size: nd.len(), cap: {lim_dec} }});\n    }}\n")
            else:
                o.append("    dec.read_to_end(&mut nd)?;\n")
            o.append(f"    let mut doc = {name}::default();\n    for (i, line) in nd.split(|&b| b == b'\\n').enumerate() {{\n        if line.is_empty() {{\n            continue;\n        }}\n")
            o.append("        if i == 0 {\n")
            o.append(f"            doc.header = Some({hdr}::from_json_slice(line)?);\n            continue;\n        }}\n")
            o.append("        let v: serde_json::Value = serde_json::from_slice(line)?;\n")
            first = True
            for rr in rows:
                disc = m.records[rr].fields[0].wire_name(m.records[rr].naming)
                kw = "if" if first else "} else if"
                o.append(f'        {kw} v.get("{disc}").is_some() {{\n            doc.{snake(rr)}s.push(serde_json::from_value(v)?);\n')
                first = False
            o.append('        } else {\n            return Err(ProtoError::ManifestLine { line: i + 1, reason: "row is neither a live nor a deleted row".into() });\n        }\n    }\n    Ok(doc)\n}\n\n')
    return "".join(o)
