"""C99 emitter: fixed-buffer structs, self-contained JSON encode/decode (no cJSON), validators, key builders.

Prefix: rrcp_ / RRCP_. Zero heap allocation; suitable for MCUs. Integers are exact
(own parser). The only external symbol is `rrcp_blake3_hook` for hashed key parts.
"""
from __future__ import annotations

from pathlib import Path

from model import Model, Record, Field, TypeRef, snake, upper_snake

HEADER = "/* @generated by protocol/rrcgen from protocol/rrcloud.protocol.toml — DO NOT EDIT. */\n"

C_PRIM = {"u8": "uint8_t", "u32": "uint32_t", "u64": "uint64_t", "i64": "int64_t", "usize": "size_t", "bool": "bool"}


def c_scalar_base(m: Model, name: str) -> str:
    """C type for a non-string, non-array leaf."""
    if name in C_PRIM:
        return C_PRIM[name]
    kind = m.kind_of(name)
    if kind == "scalar":
        return {"i64": "int64_t", "u64": "uint64_t"}[m.scalars[name].kind]
    if kind == "enum":
        return f"rrcp_{snake(name)}_t"
    if kind in ("map", "record"):
        return f"rrcp_{snake(name)}_t"
    raise ValueError(name)


def is_stringish(m: Model, t: TypeRef) -> bool:
    return t.name == "string" or (t.name in m.scalars and m.scalars[t.name].kind == "string")


def emit(m: Model, out_dir: Path) -> None:
    d = out_dir / "c"
    d.mkdir(parents=True, exist_ok=True)
    (d / "rrcloud_proto.h").write_text(header(m), encoding="utf-8")
    (d / "rrcloud_proto.c").write_text(source(m), encoding="utf-8")


def cdoc(text: str, indent: str = "") -> str:
    if not text:
        return ""
    lines = text.splitlines()
    if len(lines) == 1:
        return f"{indent}/** {lines[0]} */\n"
    return f"{indent}/**\n" + "".join(f"{indent} * {l}\n" for l in lines) + f"{indent} */\n"


def header(m: Model) -> str:
    o: list[str] = [HEADER]
    o.append(f"/* {m.protocol['description']} — protocol definition v{m.protocol['idl_version']}, wire version {m.protocol['wire_version']}. */\n")
    o.append("#pragma once\n#include <stdbool.h>\n#include <stddef.h>\n#include <stdint.h>\n\n#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n")
    o.append("/* ---- constants ---------------------------------------------------------- */\n")
    for c in m.constants.values():
        o.append(cdoc(c.doc))
        if c.type == "str":
            o.append(f'#define RRCP_{c.name} "{c.value}"\n')
        elif c.type.startswith("["):
            o.append(f"#define RRCP_{c.name}_LEN {len(c.value)}\nstatic const {C_PRIM[c.type[1:-1]]} RRCP_{c.name}[{len(c.value)}] = {{{', '.join(str(v) for v in c.value)}}};\n")
        else:
            suffix = {"u32": "u", "u64": "ull", "usize": "u", "i64": "ll"}.get(c.type, "")
            o.append(f"#define RRCP_{c.name} ({c.value}{suffix})\n")
    o.append("\n/* ---- errors ------------------------------------------------------------ */\n")
    o.append("typedef enum {\n    RRCP_OK = 0,\n    RRCP_E_INVALID = -1,            /**< a scalar failed validation */\n    RRCP_E_OVERFLOW = -2,           /**< output buffer or fixed-capacity field too small */\n"
             "    RRCP_E_SYNTAX = -3,             /**< malformed JSON */\n    RRCP_E_MISSING_FIELD = -4,      /**< a required field is absent */\n    RRCP_E_UNSUPPORTED_VERSION = -5,/**< version field outside the supported set (fail closed) */\n"
             "    RRCP_E_BAD_VALUE = -6,          /**< wrong JSON type / unknown enum value / integer out of range */\n} rrcp_err_t;\n\nconst char *rrcp_err_str(rrcp_err_t e);\n\n")
    o.append("/* ---- scalars ------------------------------------------------------------ */\n")
    for s in m.scalars.values():
        o.append(cdoc(s.doc))
        if s.kind == "string":
            o.append(f"#define RRCP_{upper_snake(s.name)}_MAX {s.buf_len}\n")
            o.append(f"rrcp_err_t rrcp_validate_{snake(s.name)}(const char *s);\n")
        else:
            o.append(f"typedef {C_PRIM[s.kind]} rrcp_{snake(s.name)}_t;\n")
    o.append("\n/* ---- enums --------------------------------------------------------------- */\n")
    for e in m.enums.values():
        o.append(cdoc(e.doc))
        o.append("typedef enum {\n")
        for v in e.values:
            o.append(f"    RRCP_{upper_snake(e.name)}_{v.name.upper()},{('  /**< ' + v.doc + ' */') if v.doc else ''}\n")
        o.append(f"    RRCP_{upper_snake(e.name)}__COUNT\n}} rrcp_{snake(e.name)}_t;\n")
        o.append(f"const char *rrcp_{snake(e.name)}_wire(rrcp_{snake(e.name)}_t v);\nbool rrcp_{snake(e.name)}_parse(const char *s, rrcp_{snake(e.name)}_t *out);\n\n")
    o.append("/* ---- maps ---------------------------------------------------------------- */\n")
    for mp in m.maps.values():
        o.append(cdoc(mp.doc))
        o.append(f"#define RRCP_{upper_snake(mp.name)}_MAX_ITEMS {mp.max_items}\n")
        o.append(f"typedef struct {{\n    size_t len;\n    struct {{\n        char key[RRCP_{upper_snake(mp.key)}_MAX + 1];\n        {C_PRIM[mp.value]} value;\n    }} items[{mp.max_items}];  /**< sorted by key */\n}} rrcp_{snake(mp.name)}_t;\n")
        o.append(f"/** Inserts/replaces (sorted). {'A zero value removes the key.' if mp.drop_zero else ''} */\nrrcp_err_t rrcp_{snake(mp.name)}_set(rrcp_{snake(mp.name)}_t *m, const char *key, {C_PRIM[mp.value]} value);\n")
        o.append(f"/** Missing keys read as 0. */\n{C_PRIM[mp.value]} rrcp_{snake(mp.name)}_get(const rrcp_{snake(mp.name)}_t *m, const char *key);\n\n")
    o.append("/* ---- records ------------------------------------------------------------- */\n")
    for r in m.records.values():
        o.append(record_h(m, r))
    o.append("/* ---- bucket keys --------------------------------------------------------- */\n")
    o.append("/** Provided by the integrator: BLAKE3-256 of `data` into `out` (used by hashed key parts). */\nextern void rrcp_blake3_hook(const uint8_t *data, size_t len, uint8_t out[32]);\n\n")
    for k in m.keys.values():
        o.append(cdoc(k.doc))
        o.append(f"/** `{k.template}` — returns length or a negative rrcp_err_t. */\nint rrcp_key_{k.name}({key_params_c(m, k)}char *out, size_t cap);\n\n")
    o.append("#ifdef __cplusplus\n}\n#endif\n")
    return "".join(o)


def key_params_c(m: Model, k) -> str:
    out = []
    for pname, ptype in k.params.items():
        if ptype in m.enums:
            out.append(f"rrcp_{snake(ptype)}_t {pname}")
        elif ptype in m.scalars and m.scalars[ptype].kind != "string":
            out.append(f"{C_PRIM[m.scalars[ptype].kind]} {pname}")
        else:
            out.append(f"const char *{pname}")
    return "".join(p + ", " for p in out)


def field_c_decl(m: Model, r: Record, f: Field) -> str:
    o = []
    if f.optional:
        o.append(f"    bool has_{f.name};\n")
    if f.type.array:
        o.append(f"    size_t {f.name}_len;\n")
        if is_stringish(m, TypeRef(f.type.name)):
            cap = f.max_length if f.type.name == "string" else m.scalars[f.type.name].buf_len
            o.append(f"    char {f.name}[{f.max_items}][{cap} + 1];\n")
        else:
            o.append(f"    {c_scalar_base(m, f.type.name)} {f.name}[{f.max_items}];\n")
    elif is_stringish(m, f.type):
        o.append(f"    char {f.name}[{m.string_buf_len(f)} + 1];\n")
    else:
        o.append(f"    {c_scalar_base(m, f.type.name)} {f.name};\n")
    return "".join(o)


def record_h(m: Model, r: Record) -> str:
    o = [cdoc(r.doc), "typedef struct {\n"]
    for f in r.fields:
        if f.doc:
            o.append(cdoc(f.doc, "    "))
        o.append(field_c_decl(m, r, f))
    o.append(f"}} rrcp_{snake(r.name)}_t;\n")
    o.append(f"/** Resets to defaults (zeroed, IDL defaults applied). */\nvoid rrcp_{snake(r.name)}_init(rrcp_{snake(r.name)}_t *v);\n")
    o.append(f"/** Validates scalars and writes one JSON document (fixed field order). Returns length or a negative rrcp_err_t. */\nint rrcp_{snake(r.name)}_encode(const rrcp_{snake(r.name)}_t *v, char *out, size_t cap);\n")
    o.append(f"/** Parses one JSON document (unknown fields ignored, required fields enforced{', version gate on `' + r.version_field + '`' if r.version_field else ''}). */\nrrcp_err_t rrcp_{snake(r.name)}_decode(const char *json, size_t len, rrcp_{snake(r.name)}_t *out);\n\n")
    return "".join(o)


# ----------------------------------------------------------------------------- source

RUNTIME_C = r'''
/* ---- JSON writer (deterministic, serde_json-compatible escaping) ------------ */
typedef struct { char *buf; size_t cap, len; bool overflow; } w_t;

static void w_putc(w_t *w, char c)
{
    if (w->overflow) return;
    if (w->len + 1 >= w->cap) { w->overflow = true; return; }
    w->buf[w->len++] = c;
    w->buf[w->len] = 0;
}
static void w_raw(w_t *w, const char *s) { while (*s) w_putc(w, *s++); }
static void w_str(w_t *w, const char *s)
{
    static const char HX[] = "0123456789abcdef";
    w_putc(w, '"');
    for (const unsigned char *p = (const unsigned char *)s; *p; p++) {
        unsigned char c = *p;
        switch (c) {
        case '"': w_raw(w, "\\\""); break;
        case '\\': w_raw(w, "\\\\"); break;
        case '\b': w_raw(w, "\\b"); break;
        case '\f': w_raw(w, "\\f"); break;
        case '\n': w_raw(w, "\\n"); break;
        case '\r': w_raw(w, "\\r"); break;
        case '\t': w_raw(w, "\\t"); break;
        default:
            if (c < 0x20) { char e[7] = {'\\', 'u', '0', '0', HX[c >> 4], HX[c & 15], 0}; w_raw(w, e); }
            else w_putc(w, (char)c);
        }
    }
    w_putc(w, '"');
}
static void w_u64(w_t *w, uint64_t v) { char b[24]; snprintf(b, sizeof b, "%llu", (unsigned long long)v); w_raw(w, b); }
static void w_i64(w_t *w, int64_t v) { char b[24]; snprintf(b, sizeof b, "%lld", (long long)v); w_raw(w, b); }
static void w_key(w_t *w, const char *k, bool *first) { if (!*first) w_putc(w, ','); *first = false; w_str(w, k); w_putc(w, ':'); }

/* ---- JSON reader (exact integers, UTF-8 output, no allocation) ---------------- */
typedef struct { const char *p, *e; } r_t;

static void r_ws(r_t *r) { while (r->p < r->e && (*r->p == ' ' || *r->p == '\t' || *r->p == '\n' || *r->p == '\r')) r->p++; }
static bool r_peek(r_t *r, char c) { r_ws(r); return r->p < r->e && *r->p == c; }
static rrcp_err_t r_expect(r_t *r, char c) { if (!r_peek(r, c)) return RRCP_E_SYNTAX; r->p++; return RRCP_OK; }

static int hexval(char c)
{
    if (c >= '0' && c <= '9') return c - '0';
    if (c >= 'a' && c <= 'f') return c - 'a' + 10;
    if (c >= 'A' && c <= 'F') return c - 'A' + 10;
    return -1;
}

static size_t utf8_put(char *out, size_t cap, size_t o, uint32_t cp, bool *ovf)
{
    char t[4]; int n;
    if (cp < 0x80) { t[0] = (char)cp; n = 1; }
    else if (cp < 0x800) { t[0] = (char)(0xc0 | (cp >> 6)); t[1] = (char)(0x80 | (cp & 0x3f)); n = 2; }
    else if (cp < 0x10000) { t[0] = (char)(0xe0 | (cp >> 12)); t[1] = (char)(0x80 | ((cp >> 6) & 0x3f)); t[2] = (char)(0x80 | (cp & 0x3f)); n = 3; }
    else { t[0] = (char)(0xf0 | (cp >> 18)); t[1] = (char)(0x80 | ((cp >> 12) & 0x3f)); t[2] = (char)(0x80 | ((cp >> 6) & 0x3f)); t[3] = (char)(0x80 | (cp & 0x3f)); n = 4; }
    if (out) { if (o + (size_t)n >= cap) { *ovf = true; return o; } memcpy(out + o, t, (size_t)n); }
    return o + (size_t)n;
}

/* Parses a JSON string into out (NUL-terminated). out==NULL just skips. */
static rrcp_err_t r_string(r_t *r, char *out, size_t cap)
{
    if (r_expect(r, '"')) return RRCP_E_SYNTAX;
    size_t o = 0; bool ovf = false;
    while (r->p < r->e) {
        unsigned char c = (unsigned char)*r->p++;
        if (c == '"') { if (out) { if (ovf) return RRCP_E_OVERFLOW; out[o] = 0; } return RRCP_OK; }
        if (c == '\\') {
            if (r->p >= r->e) return RRCP_E_SYNTAX;
            char e = *r->p++;
            uint32_t cp;
            switch (e) {
            case '"': cp = '"'; break; case '\\': cp = '\\'; break; case '/': cp = '/'; break;
            case 'b': cp = '\b'; break; case 'f': cp = '\f'; break; case 'n': cp = '\n'; break;
            case 'r': cp = '\r'; break; case 't': cp = '\t'; break;
            case 'u': {
                if (r->e - r->p < 4) return RRCP_E_SYNTAX;
                int h0 = hexval(r->p[0]), h1 = hexval(r->p[1]), h2 = hexval(r->p[2]), h3 = hexval(r->p[3]);
                if (h0 < 0 || h1 < 0 || h2 < 0 || h3 < 0) return RRCP_E_SYNTAX;
                cp = (uint32_t)((h0 << 12) | (h1 << 8) | (h2 << 4) | h3);
                r->p += 4;
                if (cp >= 0xd800 && cp <= 0xdbff && r->e - r->p >= 6 && r->p[0] == '\\' && r->p[1] == 'u') {
                    int l0 = hexval(r->p[2]), l1 = hexval(r->p[3]), l2 = hexval(r->p[4]), l3 = hexval(r->p[5]);
                    if (l0 >= 0 && l1 >= 0 && l2 >= 0 && l3 >= 0) {
                        uint32_t lo = (uint32_t)((l0 << 12) | (l1 << 8) | (l2 << 4) | l3);
                        if (lo >= 0xdc00 && lo <= 0xdfff) { cp = 0x10000 + ((cp - 0xd800) << 10) + (lo - 0xdc00); r->p += 6; }
                    }
                }
                break;
            }
            default: return RRCP_E_SYNTAX;
            }
            o = utf8_put(out, cap, o, cp, &ovf);
        } else {
            if (c < 0x20) return RRCP_E_SYNTAX;
            if (out) { if (o + 1 >= cap) ovf = true; else out[o] = (char)c; }
            o++;
        }
    }
    return RRCP_E_SYNTAX;
}

static rrcp_err_t r_u64(r_t *r, uint64_t *out)
{
    r_ws(r);
    if (r->p >= r->e || *r->p < '0' || *r->p > '9') return RRCP_E_BAD_VALUE;
    uint64_t v = 0;
    while (r->p < r->e && *r->p >= '0' && *r->p <= '9') {
        unsigned d = (unsigned)(*r->p - '0');
        if (v > (UINT64_MAX - d) / 10) return RRCP_E_BAD_VALUE;
        v = v * 10 + d; r->p++;
    }
    if (r->p < r->e && (*r->p == '.' || *r->p == 'e' || *r->p == 'E')) return RRCP_E_BAD_VALUE; /* integers only */
    *out = v;
    return RRCP_OK;
}

static rrcp_err_t r_i64(r_t *r, int64_t *out)
{
    r_ws(r);
    bool neg = false;
    if (r->p < r->e && *r->p == '-') { neg = true; r->p++; }
    uint64_t u;
    rrcp_err_t e = r_u64(r, &u);
    if (e) return e;
    if (neg) { if (u > (uint64_t)INT64_MAX + 1u) return RRCP_E_BAD_VALUE; *out = (int64_t)(0 - u); }
    else { if (u > (uint64_t)INT64_MAX) return RRCP_E_BAD_VALUE; *out = (int64_t)u; }
    return RRCP_OK;
}

static rrcp_err_t r_bool(r_t *r, bool *out)
{
    r_ws(r);
    if (r->e - r->p >= 4 && !memcmp(r->p, "true", 4)) { r->p += 4; *out = true; return RRCP_OK; }
    if (r->e - r->p >= 5 && !memcmp(r->p, "false", 5)) { r->p += 5; *out = false; return RRCP_OK; }
    return RRCP_E_BAD_VALUE;
}

static rrcp_err_t r_skip(r_t *r, int depth)
{
    if (depth > 32) return RRCP_E_SYNTAX;
    r_ws(r);
    if (r->p >= r->e) return RRCP_E_SYNTAX;
    char c = *r->p;
    if (c == '"') return r_string(r, NULL, 0);
    if (c == '{' || c == '[') {
        char close = c == '{' ? '}' : ']';
        r->p++;
        if (r_peek(r, close)) { r->p++; return RRCP_OK; }
        for (;;) {
            if (c == '{') { rrcp_err_t e = r_string(r, NULL, 0); if (e) return e; if (r_expect(r, ':')) return RRCP_E_SYNTAX; }
            rrcp_err_t e = r_skip(r, depth + 1);
            if (e) return e;
            if (r_peek(r, ',')) { r->p++; continue; }
            if (r_peek(r, close)) { r->p++; return RRCP_OK; }
            return RRCP_E_SYNTAX;
        }
    }
    if (c == 't' || c == 'f') { bool b; return r_bool(r, &b); }
    if (c == 'n') { if (r->e - r->p >= 4 && !memcmp(r->p, "null", 4)) { r->p += 4; return RRCP_OK; } return RRCP_E_SYNTAX; }
    if (c == '-' || (c >= '0' && c <= '9')) {
        r->p++;
        while (r->p < r->e && (( *r->p >= '0' && *r->p <= '9') || *r->p == '.' || *r->p == 'e' || *r->p == 'E' || *r->p == '+' || *r->p == '-')) r->p++;
        return RRCP_OK;
    }
    return RRCP_E_SYNTAX;
}

/* Object iteration helpers: begin → loop { next_key → value → sep } */
static rrcp_err_t r_obj_begin(r_t *r, bool *empty) { if (r_expect(r, '{')) return RRCP_E_SYNTAX; *empty = r_peek(r, '}'); if (*empty) r->p++; return RRCP_OK; }
static rrcp_err_t r_obj_key(r_t *r, char *key, size_t cap) { rrcp_err_t e = r_string(r, key, cap); if (e == RRCP_E_OVERFLOW) { /* unknown long key: skip it */ key[0] = 0; e = RRCP_OK; } if (e) return e; return r_expect(r, ':'); }
/* returns 1 = more members, 0 = end, negative = error */
static int r_obj_sep(r_t *r) { if (r_peek(r, ',')) { r->p++; return 1; } if (r_peek(r, '}')) { r->p++; return 0; } return RRCP_E_SYNTAX; }
static rrcp_err_t r_arr_begin(r_t *r, bool *empty) { if (r_expect(r, '[')) return RRCP_E_SYNTAX; *empty = r_peek(r, ']'); if (*empty) r->p++; return RRCP_OK; }
static int r_arr_sep(r_t *r) { if (r_peek(r, ',')) { r->p++; return 1; } if (r_peek(r, ']')) { r->p++; return 0; } return RRCP_E_SYNTAX; }
static rrcp_err_t r_end(r_t *r) { r_ws(r); return r->p == r->e ? RRCP_OK : RRCP_E_SYNTAX; }

/* ---- validators ------------------------------------------------------------- */
static bool is_lower_hex(const char *s, size_t len)
{
    if (strlen(s) != len) return false;
    for (; *s; s++) if (!((*s >= '0' && *s <= '9') || (*s >= 'a' && *s <= 'f'))) return false;
    return true;
}

static bool is_uuid4_lower(const char *s)
{
    if (strlen(s) != 36) return false;
    for (int i = 0; i < 36; i++) {
        char c = s[i];
        switch (i) {
        case 8: case 13: case 18: case 23: if (c != '-') return false; break;
        case 14: if (c != '4') return false; break;
        case 19: if (!(c == '8' || c == '9' || c == 'a' || c == 'b')) return false; break;
        default: if (!((c >= '0' && c <= '9') || (c >= 'a' && c <= 'f'))) return false;
        }
    }
    return true;
}

static int utf8_decode(const unsigned char *p, uint32_t *cp)
{
    if (p[0] < 0x80) { *cp = p[0]; return 1; }
    if ((p[0] & 0xe0) == 0xc0) { if ((p[1] & 0xc0) != 0x80) return 0; *cp = ((uint32_t)(p[0] & 0x1f) << 6) | (p[1] & 0x3f); return *cp >= 0x80 ? 2 : 0; }
    if ((p[0] & 0xf0) == 0xe0) { if ((p[1] & 0xc0) != 0x80 || (p[2] & 0xc0) != 0x80) return 0; *cp = ((uint32_t)(p[0] & 0x0f) << 12) | ((uint32_t)(p[1] & 0x3f) << 6) | (p[2] & 0x3f); return (*cp >= 0x800 && !(*cp >= 0xd800 && *cp <= 0xdfff)) ? 3 : 0; }
    if ((p[0] & 0xf8) == 0xf0) { if ((p[1] & 0xc0) != 0x80 || (p[2] & 0xc0) != 0x80 || (p[3] & 0xc0) != 0x80) return 0; *cp = ((uint32_t)(p[0] & 0x07) << 18) | ((uint32_t)(p[1] & 0x3f) << 12) | ((uint32_t)(p[2] & 0x3f) << 6) | (p[3] & 0x3f); return (*cp >= 0x10000 && *cp <= 0x10ffff) ? 4 : 0; }
    return 0;
}

/* Conservative NFC check without normalization tables: combining marks and conjoining
 * jamo mean "not NFC". Camera/ASCII keys are unaffected; the Rust reference uses full tables. */
static bool looks_decomposed(uint32_t cp)
{
    return (cp >= 0x0300 && cp <= 0x036f) || (cp >= 0x1ab0 && cp <= 0x1aff) || (cp >= 0x1dc0 && cp <= 0x1dff) ||
           (cp >= 0x20d0 && cp <= 0x20ff) || (cp >= 0xfe20 && cp <= 0xfe2f) || (cp >= 0x1100 && cp <= 0x11ff) ||
           (cp >= 0x3099 && cp <= 0x309a) || (cp >= 0xf900 && cp <= 0xfaff) || (cp >= 0x2f800 && cp <= 0x2fa1f);
}

static int lc(int c) { return (c >= 'A' && c <= 'Z') ? c + 32 : c; }

static bool seg_windows_reserved(const char *seg, size_t len)
{
    size_t base = 0;
    while (base < len && seg[base] != '.') base++;
    while (base > 0 && seg[base - 1] == ' ') base--;
    if (base == 3) {
        static const char *r3[] = {"con", "prn", "aux", "nul"};
        for (int i = 0; i < 4; i++) if (lc(seg[0]) == r3[i][0] && lc(seg[1]) == r3[i][1] && lc(seg[2]) == r3[i][2]) return true;
        return false;
    }
    if (base > 3 && ((lc(seg[0]) == 'c' && lc(seg[1]) == 'o' && lc(seg[2]) == 'm') || (lc(seg[0]) == 'l' && lc(seg[1]) == 'p' && lc(seg[2]) == 't'))) {
        size_t rest = base - 3;
        const unsigned char *q = (const unsigned char *)seg + 3;
        if (rest == 1) return q[0] >= '1' && q[0] <= '9';
        if (rest == 2) return q[0] == 0xc2 && (q[1] == 0xb9 || q[1] == 0xb2 || q[1] == 0xb3);
    }
    return false;
}

static rrcp_err_t validate_relkey_rules(const char *s)
{
    if (!s || !*s) return RRCP_E_INVALID;
    for (const unsigned char *p = (const unsigned char *)s; *p;) {
        uint32_t cp; int l = utf8_decode(p, &cp);
        if (!l) return RRCP_E_INVALID;
        if (cp == '\\' || cp == ':' || cp < 0x20 || cp == 0x7f || (cp >= 0x80 && cp < 0xa0) || looks_decomposed(cp)) return RRCP_E_INVALID;
        p += l;
    }
    if (s[0] == '/') return RRCP_E_INVALID;
    const char *seg = s;
    for (;;) {
        const char *end = strchr(seg, '/');
        size_t len = end ? (size_t)(end - seg) : strlen(seg);
        if (len == 0 || (len == 1 && seg[0] == '.') || (len == 2 && seg[0] == '.' && seg[1] == '.')) return RRCP_E_INVALID;
        if (seg[len - 1] == '.' || seg[len - 1] == ' ') return RRCP_E_INVALID;
        if (len >= 4 && !memcmp(seg, RRCP_ENGINE_TEMP_PREFIX, 4)) return RRCP_E_INVALID;
        if (seg_windows_reserved(seg, len)) return RRCP_E_INVALID;
        if (!end) break;
        seg = end + 1;
    }
    return RRCP_OK;
}

const char *rrcp_err_str(rrcp_err_t e)
{
    switch (e) {
    case RRCP_OK: return "ok";
    case RRCP_E_INVALID: return "invalid scalar";
    case RRCP_E_OVERFLOW: return "buffer overflow";
    case RRCP_E_SYNTAX: return "json syntax";
    case RRCP_E_MISSING_FIELD: return "missing required field";
    case RRCP_E_UNSUPPORTED_VERSION: return "unsupported version";
    case RRCP_E_BAD_VALUE: return "bad value";
    }
    return "?";
}
'''


def source(m: Model) -> str:
    o: list[str] = [HEADER, '#include "rrcloud_proto.h"\n#include <stdio.h>\n#include <string.h>\n', RUNTIME_C, "\n"]
    # scalar validators
    for s in m.scalars.values():
        if s.kind != "string":
            continue
        o.append(f"rrcp_err_t rrcp_validate_{snake(s.name)}(const char *s)\n{{\n    if (!s || strlen(s) > RRCP_{upper_snake(s.name)}_MAX) return RRCP_E_INVALID;\n")
        if s.format == "uuid4-lower":
            o.append("    return is_uuid4_lower(s) ? RRCP_OK : RRCP_E_INVALID;\n")
        elif s.format == "lower-hex":
            o.append(f"    return is_lower_hex(s, {s.length}) ? RRCP_OK : RRCP_E_INVALID;\n")
        elif s.format == "relkey":
            o.append("    return validate_relkey_rules(s);\n")
        else:
            o.append("    return RRCP_OK;\n")
        o.append("}\n\n")
    # enums
    for e in m.enums.values():
        t = f"rrcp_{snake(e.name)}_t"
        o.append(f"static const char *const {snake(e.name)}_wire[] = {{{', '.join(repr(v.wire).replace(chr(39), chr(34)) for v in e.values)}}};\n")
        o.append(f"const char *rrcp_{snake(e.name)}_wire({t} v) {{ return (unsigned)v < RRCP_{upper_snake(e.name)}__COUNT ? {snake(e.name)}_wire[v] : \"?\"; }}\n")
        o.append(f"bool rrcp_{snake(e.name)}_parse(const char *s, {t} *out)\n{{\n    for (unsigned i = 0; i < RRCP_{upper_snake(e.name)}__COUNT; i++) if (!strcmp(s, {snake(e.name)}_wire[i])) {{ *out = ({t})i; return true; }}\n    return false;\n}}\n\n")
    # maps
    for mp in m.maps.values():
        t = f"rrcp_{snake(mp.name)}_t"
        vt = C_PRIM[mp.value]
        o.append(f"rrcp_err_t rrcp_{snake(mp.name)}_set({t} *m, const char *key, {vt} value)\n{{\n")
        o.append(f"    if (rrcp_validate_{snake(mp.key)}(key)) return RRCP_E_INVALID;\n    size_t i = 0;\n    while (i < m->len && strcmp(m->items[i].key, key) < 0) i++;\n")
        o.append("    bool exists = i < m->len && !strcmp(m->items[i].key, key);\n")
        if mp.drop_zero:
            o.append("    if (value == 0) {\n        if (exists) { memmove(&m->items[i], &m->items[i + 1], (m->len - i - 1) * sizeof m->items[0]); m->len--; }\n        return RRCP_OK;\n    }\n")
        o.append(f"    if (!exists) {{\n        if (m->len >= {mp.max_items}) return RRCP_E_OVERFLOW;\n        memmove(&m->items[i + 1], &m->items[i], (m->len - i) * sizeof m->items[0]);\n        m->len++;\n        snprintf(m->items[i].key, sizeof m->items[i].key, \"%s\", key);\n    }}\n    m->items[i].value = value;\n    return RRCP_OK;\n}}\n")
        o.append(f"{vt} rrcp_{snake(mp.name)}_get(const {t} *m, const char *key)\n{{\n    for (size_t i = 0; i < m->len; i++) if (!strcmp(m->items[i].key, key)) return m->items[i].value;\n    return 0;\n}}\n")
        o.append(f"static void {snake(mp.name)}_write(w_t *w, const {t} *m)\n{{\n    w_putc(w, '{{');\n    for (size_t i = 0; i < m->len; i++) {{ if (i) w_putc(w, ','); w_str(w, m->items[i].key); w_putc(w, ':'); w_u64(w, (uint64_t)m->items[i].value); }}\n    w_putc(w, '}}');\n}}\n")
        o.append(f"static rrcp_err_t {snake(mp.name)}_read(r_t *r, {t} *m)\n{{\n    m->len = 0;\n    bool empty;\n    rrcp_err_t e = r_obj_begin(r, &empty);\n    if (e) return e;\n    if (empty) return RRCP_OK;\n    for (;;) {{\n        char key[RRCP_{upper_snake(mp.key)}_MAX + 1];\n        e = r_string(r, key, sizeof key);\n        if (e) return e;\n        if (r_expect(r, ':')) return RRCP_E_SYNTAX;\n        uint64_t v;\n        e = r_u64(r, &v);\n        if (e) return e;\n")
        if mp.value == "u32":
            o.append("        if (v > UINT32_MAX) return RRCP_E_BAD_VALUE;\n")
        o.append(f"        e = rrcp_{snake(mp.name)}_set(m, key, ({vt})v);\n        if (e) return e;\n        int more = r_obj_sep(r);\n        if (more < 0) return (rrcp_err_t)more;\n        if (!more) return RRCP_OK;\n    }}\n}}\n\n")
    # records
    for r in m.records.values():
        o.append(record_c(m, r))
    # keys
    o.append(KEY_HELPERS_C)
    for k in m.keys.values():
        o.append(key_c(m, k))
    return "".join(o)


KEY_HELPERS_C = r'''
/* ---- keys ------------------------------------------------------------------- */
static int k_put(char *out, size_t cap, size_t *pos, const char *s)
{
    size_t n = strlen(s);
    if (*pos + n + 1 > cap) return RRCP_E_OVERFLOW;
    memcpy(out + *pos, s, n + 1);
    *pos += n;
    return RRCP_OK;
}
static void k_blake3_32(const char *s, char out[33])
{
    static const char HX[] = "0123456789abcdef";
    uint8_t d[32];
    rrcp_blake3_hook((const uint8_t *)s, strlen(s), d);
    for (int i = 0; i < 16; i++) { out[2 * i] = HX[d[i] >> 4]; out[2 * i + 1] = HX[d[i] & 15]; }
    out[32] = 0;
}
static bool is_hex_n(const char *s, size_t n) { return is_lower_hex(s, n); }
static bool is_username(const char *s)
{
    size_t n = strlen(s);
    if (n == 0 || n > 128 || !strcmp(s, ".") || !strcmp(s, "..")) return false;
    for (; *s; s++) if (!((*s >= 'a' && *s <= 'z') || (*s >= 'A' && *s <= 'Z') || (*s >= '0' && *s <= '9') || *s == '.' || *s == '_' || *s == '-')) return false;
    return true;
}
'''


def key_c(m: Model, k) -> str:
    o = [f"int rrcp_key_{k.name}({key_params_c(m, k)}char *out, size_t cap)\n{{\n    size_t pos = 0;\n    if (cap) out[0] = 0;\n"]
    for pname, ptype in k.params.items():
        if ptype in m.scalars and m.scalars[ptype].kind == "string":
            o.append(f"    if (rrcp_validate_{snake(ptype)}({pname})) return RRCP_E_INVALID;\n")
        elif ptype == "hex6":
            o.append(f"    if (!is_hex_n({pname}, 6)) return RRCP_E_INVALID;\n")
        elif ptype == "username":
            o.append(f"    if (!is_username({pname})) return RRCP_E_INVALID;\n")
    for p in k.parts:
        if p.literal is not None:
            o.append(f'    if (k_put(out, cap, &pos, "{p.literal}")) return RRCP_E_OVERFLOW;\n')
        elif p.fmt == "hex16":
            o.append(f'    {{ char b[17]; snprintf(b, sizeof b, "%016llx", (unsigned long long){p.param}); if (k_put(out, cap, &pos, b)) return RRCP_E_OVERFLOW; }}\n')
        elif p.fmt == "blake3_32":
            o.append(f"    {{ char h[33]; k_blake3_32({p.param}, h); if (k_put(out, cap, &pos, h)) return RRCP_E_OVERFLOW; }}\n")
        else:
            ptype = k.params[p.param]
            if ptype in m.enums:
                o.append(f"    if (k_put(out, cap, &pos, rrcp_{snake(ptype)}_wire({p.param}))) return RRCP_E_OVERFLOW;\n")
            elif ptype in m.scalars and m.scalars[ptype].kind != "string":
                o.append(f'    {{ char b[24]; snprintf(b, sizeof b, "%llu", (unsigned long long){p.param}); if (k_put(out, cap, &pos, b)) return RRCP_E_OVERFLOW; }}\n')
            else:
                o.append(f"    if (k_put(out, cap, &pos, {p.param})) return RRCP_E_OVERFLOW;\n")
    o.append("    return (int)pos;\n}\n\n")
    return "".join(o)


def c_literal(m: Model, f: Field) -> str:
    v = f.default
    if f.type.name == "bool":
        return "true" if v else "false"
    if f.type.name == "string":
        return '"' + str(v).replace('"', '\\"') + '"'
    return str(v)


def record_c(m: Model, r: Record) -> str:
    t = f"rrcp_{snake(r.name)}_t"
    o: list[str] = []
    # init
    o.append(f"void rrcp_{snake(r.name)}_init({t} *v)\n{{\n    memset(v, 0, sizeof *v);\n")
    for f in r.fields:
        if f.has_default and not f.type.array:
            if f.type.name == "string":
                o.append(f'    snprintf(v->{f.name}, sizeof v->{f.name}, "%s", {c_literal(m, f)});\n')
            else:
                o.append(f"    v->{f.name} = {c_literal(m, f)};\n")
        elif m.kind_of(f.type.name) == "record" and not f.type.array:
            o.append(f"    rrcp_{snake(f.type.name)}_init(&v->{f.name});\n")
    o.append("}\n\n")
    # encode (static writer form + public)
    o.append(f"static rrcp_err_t {snake(r.name)}_write(w_t *w, const {t} *v)\n{{\n    bool first = true;\n    w_putc(w, '{{');\n")
    for f in r.fields:
        wire = f.wire_name(r.naming)
        ind = "    "
        if f.optional:
            o.append(f"    if (v->has_{f.name}) {{\n")
            ind = "        "
        o.append(f'{ind}w_key(w, "{wire}", &first);\n')
        o.append(write_value(m, f, f"v->{f.name}", ind))
        if f.optional:
            o.append("    }\n")
    o.append("    w_putc(w, '}');\n    return RRCP_OK;\n}\n\n")
    o.append(f"int rrcp_{snake(r.name)}_encode(const {t} *v, char *out, size_t cap)\n{{\n    w_t w = {{out, cap, 0, cap == 0}};\n    if (cap) out[0] = 0;\n    rrcp_err_t e = {snake(r.name)}_write(&w, v);\n    if (e) return e;\n    return w.overflow ? RRCP_E_OVERFLOW : (int)w.len;\n}}\n\n")
    # decode
    o.append(f"static rrcp_err_t {snake(r.name)}_read(r_t *r, {t} *v)\n{{\n    rrcp_{snake(r.name)}_init(v);\n    uint32_t seen = 0;\n    (void)seen;\n    bool empty;\n    rrcp_err_t e = r_obj_begin(r, &empty);\n    if (e) return e;\n    if (!empty) for (;;) {{\n        char key[64];\n        e = r_obj_key(r, key, sizeof key);\n        if (e) return e;\n")
    first = True
    for i, f in enumerate(r.fields):
        wire = f.wire_name(r.naming)
        kw = "if" if first else "} else if"
        first = False
        o.append(f'        {kw} (!strcmp(key, "{wire}")) {{\n')
        o.append(read_value(m, f, f"v->{f.name}", "            "))
        if f.optional:
            o.append(f"            v->has_{f.name} = true;\n")
        else:
            o.append(f"            seen |= 1u << {i};\n")
    o.append("        } else {\n            e = r_skip(r, 0);\n            if (e) return e;\n        }\n")
    o.append("        int more = r_obj_sep(r);\n        if (more < 0) return (rrcp_err_t)more;\n        if (!more) break;\n    }\n")
    req_mask = 0
    for i, f in enumerate(r.fields):
        if f.required:
            req_mask |= 1 << i
    if req_mask:
        o.append(f"    if ((seen & 0x{req_mask:x}u) != 0x{req_mask:x}u) return RRCP_E_MISSING_FIELD;\n")
    o.append("    return RRCP_OK;\n}\n\n")
    o.append(f"rrcp_err_t rrcp_{snake(r.name)}_decode(const char *json, size_t len, {t} *out)\n{{\n    r_t r = {{json, json + len}};\n")
    if r.version_field:
        vers = ", ".join(str(x) for x in r.supported_versions)
        o.append(f"    /* min-reader gate: locate `{r.version_field}` before decoding anything else */\n    {{\n        r_t probe = r;\n        bool empty;\n        if (r_obj_begin(&probe, &empty)) return RRCP_E_SYNTAX;\n        bool found = false;\n        if (!empty) for (;;) {{\n            char key[64];\n            if (r_obj_key(&probe, key, sizeof key)) return RRCP_E_SYNTAX;\n            if (!strcmp(key, \"{r.version_field}\")) {{\n                uint64_t ver;\n                if (r_u64(&probe, &ver)) return RRCP_E_BAD_VALUE;\n                static const uint64_t ok[] = {{{vers}}};\n                bool sup = false;\n                for (size_t i = 0; i < sizeof ok / sizeof ok[0]; i++) if (ok[i] == ver) sup = true;\n                if (!sup) return RRCP_E_UNSUPPORTED_VERSION;\n                found = true;\n            }} else if (r_skip(&probe, 0)) return RRCP_E_SYNTAX;\n            int more = r_obj_sep(&probe);\n            if (more < 0) return RRCP_E_SYNTAX;\n            if (!more) break;\n        }}\n        if (!found) return RRCP_E_MISSING_FIELD;\n    }}\n")
    o.append(f"    rrcp_err_t e = {snake(r.name)}_read(&r, out);\n    if (e) return e;\n    return r_end(&r);\n}}\n\n")
    return "".join(o)


def write_value(m: Model, f: Field, expr: str, ind: str) -> str:
    t = f.type
    if t.array:
        inner = TypeRef(t.name)
        o = [f"{ind}w_putc(w, '[');\n{ind}for (size_t i = 0; i < {expr}_len; i++) {{\n{ind}    if (i) w_putc(w, ',');\n"]
        o.append(write_leaf(m, inner, f"{expr}[i]", ind + "    ", f))
        o.append(f"{ind}}}\n{ind}w_putc(w, ']');\n")
        return "".join(o)
    return write_leaf(m, t, expr, ind, f)


def write_leaf(m: Model, t: TypeRef, expr: str, ind: str, f: Field) -> str:
    n = t.name
    if n == "bool":
        return f'{ind}w_raw(w, {expr} ? "true" : "false");\n'
    if n in ("u8", "u32", "u64", "usize"):
        return f"{ind}w_u64(w, (uint64_t){expr});\n"
    if n == "i64":
        return f"{ind}w_i64(w, {expr});\n"
    if n == "string":
        return f"{ind}w_str(w, {expr});\n"
    kind = m.kind_of(n)
    if kind == "scalar":
        s = m.scalars[n]
        if s.kind == "string":
            return f"{ind}if (rrcp_validate_{snake(n)}({expr})) return RRCP_E_INVALID;\n{ind}w_str(w, {expr});\n"
        return f"{ind}w_i64(w, (int64_t){expr});\n" if s.kind == "i64" else f"{ind}w_u64(w, (uint64_t){expr});\n"
    if kind == "enum":
        return f"{ind}w_str(w, rrcp_{snake(n)}_wire({expr}));\n"
    if kind == "map":
        return f"{ind}{snake(n)}_write(w, &{expr});\n"
    if kind == "record":
        return f"{ind}{{ rrcp_err_t e2 = {snake(n)}_write(w, &{expr}); if (e2) return e2; }}\n"
    raise ValueError(n)


def read_value(m: Model, f: Field, expr: str, ind: str) -> str:
    t = f.type
    if t.array:
        inner = TypeRef(t.name)
        o = [f"{ind}{{\n{ind}    bool aempty;\n{ind}    e = r_arr_begin(r, &aempty);\n{ind}    if (e) return e;\n{ind}    {expr}_len = 0;\n{ind}    if (!aempty) for (;;) {{\n{ind}        if ({expr}_len >= {f.max_items}) return RRCP_E_OVERFLOW;\n"]
        o.append(read_leaf(m, inner, f"{expr}[{expr}_len]", ind + "        ", f))
        o.append(f"{ind}        {expr}_len++;\n{ind}        int amore = r_arr_sep(r);\n{ind}        if (amore < 0) return (rrcp_err_t)amore;\n{ind}        if (!amore) break;\n{ind}    }}\n{ind}}}\n")
        return "".join(o)
    return read_leaf(m, t, expr, ind, f)


def read_leaf(m: Model, t: TypeRef, expr: str, ind: str, f: Field) -> str:
    n = t.name
    if n == "bool":
        return f"{ind}e = r_bool(r, &{expr});\n{ind}if (e) return e;\n"
    if n in ("u8", "u32", "u64", "usize"):
        lim = {"u8": "UINT8_MAX", "u32": "UINT32_MAX", "u64": "UINT64_MAX", "usize": "SIZE_MAX"}[n]
        return f"{ind}{{ uint64_t u; e = r_u64(r, &u); if (e) return e; if (u > {lim}) return RRCP_E_BAD_VALUE; {expr} = ({C_PRIM[n]})u; }}\n"
    if n == "i64":
        return f"{ind}e = r_i64(r, &{expr});\n{ind}if (e) return e;\n"
    if n == "string":
        return f"{ind}e = r_string(r, {expr}, sizeof {expr});\n{ind}if (e) return e;\n"
    kind = m.kind_of(n)
    if kind == "scalar":
        s = m.scalars[n]
        if s.kind == "string":
            return f"{ind}e = r_string(r, {expr}, sizeof {expr});\n{ind}if (e) return e;\n{ind}if (rrcp_validate_{snake(n)}({expr})) return RRCP_E_INVALID;\n"
        if s.kind == "i64":
            return f"{ind}e = r_i64(r, &{expr});\n{ind}if (e) return e;\n"
        return f"{ind}e = r_u64(r, &{expr});\n{ind}if (e) return e;\n"
    if kind == "enum":
        return f"{ind}{{ char ev[32]; e = r_string(r, ev, sizeof ev); if (e) return e; if (!rrcp_{snake(n)}_parse(ev, &{expr})) return RRCP_E_BAD_VALUE; }}\n"
    if kind == "map":
        return f"{ind}e = {snake(n)}_read(r, &{expr});\n{ind}if (e) return e;\n"
    if kind == "record":
        return f"{ind}e = {snake(n)}_read(r, &{expr});\n{ind}if (e) return e;\n"
    raise ValueError(n)
