"""C++17 emitter: header-only idiomatic wrapper over the generated C API (std::string/optional/vector/map)."""
from __future__ import annotations

from pathlib import Path

from model import Model, Record, Field, TypeRef, snake, upper_snake

HEADER = "// @generated by protocol/rrcgen from protocol/rrcloud.protocol.toml — DO NOT EDIT.\n"
CPP_PRIM = {"u8": "uint8_t", "u32": "uint32_t", "u64": "uint64_t", "i64": "int64_t", "usize": "size_t", "bool": "bool", "string": "std::string"}


def cpp_base(m: Model, name: str) -> str:
    if name in CPP_PRIM:
        return CPP_PRIM[name]
    kind = m.kind_of(name)
    if kind == "scalar":
        s = m.scalars[name]
        return "std::string" if s.kind == "string" else {"i64": "int64_t", "u64": "uint64_t"}[s.kind]
    if kind == "enum":
        return name
    if kind == "map":
        return f"std::map<std::string, {CPP_PRIM[m.maps[name].value]}>"
    return name


def cpp_type(m: Model, f: Field) -> str:
    base = cpp_base(m, f.type.name)
    if f.type.array:
        base = f"std::vector<{base}>"
    return f"std::optional<{base}>" if f.optional else base


def emit(m: Model, out_dir: Path) -> None:
    d = out_dir / "c"
    d.mkdir(parents=True, exist_ok=True)
    (d / "rrcloud_proto.hpp").write_text(hpp(m), encoding="utf-8")


def hpp(m: Model) -> str:
    o: list[str] = [HEADER, "#pragma once\n#include <cstdint>\n#include <cstring>\n#include <map>\n#include <optional>\n#include <stdexcept>\n#include <string>\n#include <string_view>\n#include <vector>\n\n#include \"rrcloud_proto.h\"\n\nnamespace rrcloud::proto {\n\n"]
    o.append("/// Thrown by the from_json/encode wrappers.\nstruct Error : std::runtime_error {\n    rrcp_err_t code;\n    explicit Error(rrcp_err_t c) : std::runtime_error(rrcp_err_str(c)), code(c) {}\n};\n\n")
    o.append("namespace detail {\ninline void check(int rc) { if (rc < 0) throw Error(static_cast<rrcp_err_t>(rc)); }\ninline void copy_str(char *dst, size_t cap, const std::string &s) { if (s.size() >= cap) throw Error(RRCP_E_OVERFLOW); std::memcpy(dst, s.data(), s.size()); dst[s.size()] = 0; }\n}  // namespace detail\n\n")
    o.append("// ---- constants\n")
    for c in m.constants.values():
        if c.type == "str":
            o.append(f"inline constexpr std::string_view {c.name} = RRCP_{c.name};\n")
        elif c.type.startswith("["):
            o.append(f"inline constexpr {CPP_PRIM[c.type[1:-1]]} {c.name}[] = {{{', '.join(str(v) for v in c.value)}}};\n")
        else:
            o.append(f"inline constexpr {CPP_PRIM[c.type]} {c.name} = RRCP_{c.name};\n")
    o.append("\n// ---- enums\n")
    for e in m.enums.values():
        o.append(f"enum class {e.name} : int {{\n")
        for v in e.values:
            o.append(f"    {v.name} = RRCP_{upper_snake(e.name)}_{v.name.upper()},\n")
        o.append("};\n")
        o.append(f"inline const char *to_wire({e.name} v) {{ return rrcp_{snake(e.name)}_wire(static_cast<rrcp_{snake(e.name)}_t>(v)); }}\n")
        o.append(f"inline std::optional<{e.name}> {snake(e.name)}_from_wire(std::string_view s) {{ rrcp_{snake(e.name)}_t v; std::string z(s); if (!rrcp_{snake(e.name)}_parse(z.c_str(), &v)) return std::nullopt; return static_cast<{e.name}>(v); }}\n\n")
    o.append("// ---- validators\n")
    for s in m.scalars.values():
        if s.kind == "string":
            o.append(f"inline bool is_valid_{snake(s.name)}(std::string_view s) {{ std::string z(s); return rrcp_validate_{snake(s.name)}(z.c_str()) == RRCP_OK; }}\n")
    o.append("\n// ---- records\n")
    for r in m.records.values():
        o.append(record_hpp(m, r))
    o.append("// ---- bucket keys\n")
    for k in m.keys.values():
        args = []
        call = []
        for pname, ptype in k.params.items():
            if ptype in m.enums:
                args.append(f"{ptype} {pname}")
                call.append(f"static_cast<rrcp_{snake(ptype)}_t>({pname})")
            elif ptype in m.scalars and m.scalars[ptype].kind != "string":
                args.append(f"{CPP_PRIM[m.scalars[ptype].kind]} {pname}")
                call.append(pname)
            else:
                args.append(f"const std::string &{pname}")
                call.append(f"{pname}.c_str()")
        o.append(f"/// `{k.template}`\ninline std::string key_{k.name}({', '.join(args)}) {{\n    char buf[2048];\n    int n = rrcp_key_{k.name}({''.join(c + ', ' for c in call)}buf, sizeof buf);\n    detail::check(n);\n    return std::string(buf, static_cast<size_t>(n));\n}}\n\n")
    o.append("}  // namespace rrcloud::proto\n")
    return "".join(o)


def record_hpp(m: Model, r: Record) -> str:
    ct = f"rrcp_{snake(r.name)}_t"
    o = [f"struct {r.name} {{\n"]
    for f in r.fields:
        o.append(f"    {cpp_type(m, f)} {f.name}{{}};\n")
    o.append("\n")
    # to_c
    o.append(f"    void to_c({ct} &c) const {{\n        rrcp_{snake(r.name)}_init(&c);\n")
    for f in r.fields:
        src = f"(*{f.name})" if f.optional else f.name
        body = assign_to_c(m, f, src, f"c.{f.name}", "        ")
        if f.optional:
            o.append(f"        if ({f.name}) {{\n            c.has_{f.name} = true;\n{body}        }}\n")
        else:
            o.append(body)
    o.append("    }\n")
    # from_c
    o.append(f"    static {r.name} from_c(const {ct} &c) {{\n        {r.name} v;\n")
    for f in r.fields:
        body = assign_from_c(m, f, f"c.{f.name}", "            " if f.optional else "        ")
        if f.optional:
            o.append(f"        if (c.has_{f.name}) {{\n{body}        }}\n")
        else:
            o.append(body)
    o.append("        return v;\n    }\n")
    o.append(f"    std::string to_json() const {{\n        {ct} c;\n        to_c(c);\n        char buf[8192];\n        int n = rrcp_{snake(r.name)}_encode(&c, buf, sizeof buf);\n        detail::check(n);\n        return std::string(buf, static_cast<size_t>(n));\n    }}\n")
    o.append(f"    static {r.name} from_json(std::string_view json) {{\n        {ct} c;\n        detail::check(rrcp_{snake(r.name)}_decode(json.data(), json.size(), &c));\n        return from_c(c);\n    }}\n}};\n\n")
    return "".join(o)


def leaf_to_c(m: Model, t: str, src: str, dst: str, ind: str) -> str:
    kind = "primitive" if t in CPP_PRIM else m.kind_of(t)
    if t == "string" or (kind == "scalar" and m.scalars[t].kind == "string"):
        return f"{ind}detail::copy_str({dst}, sizeof {dst}, {src});\n"
    if kind == "enum":
        return f"{ind}{dst} = static_cast<rrcp_{snake(t)}_t>({src});\n"
    if kind == "map":
        return f"{ind}{dst}.len = 0;\n{ind}for (const auto &kv : {src}) detail::check(rrcp_{snake(t)}_set(&{dst}, kv.first.c_str(), kv.second));\n"
    if kind == "record":
        return f"{ind}{src}.to_c({dst});\n"
    return f"{ind}{dst} = {src};\n"


def assign_to_c(m: Model, f: Field, src: str, dst: str, ind: str) -> str:
    if f.type.array:
        o = [f"{ind}if ({src}.size() > {f.max_items}) throw Error(RRCP_E_OVERFLOW);\n{ind}{dst}_len = {src}.size();\n{ind}for (size_t i = 0; i < {src}.size(); i++) {{\n"]
        o.append(leaf_to_c(m, f.type.name, f"{src}[i]", f"{dst}[i]", ind + "    "))
        o.append(f"{ind}}}\n")
        return "".join(o)
    return leaf_to_c(m, f.type.name, src, dst, ind)


def leaf_from_c(m: Model, t: str, src: str, ind: str) -> str:
    """expression producing the C++ value"""
    kind = "primitive" if t in CPP_PRIM else m.kind_of(t)
    if t == "string" or (kind == "scalar" and m.scalars[t].kind == "string"):
        return f"std::string({src})"
    if kind == "enum":
        return f"static_cast<{t}>({src})"
    if kind == "record":
        return f"{t}::from_c({src})"
    return src


def assign_from_c(m: Model, f: Field, src: str, ind: str) -> str:
    t = f.type.name
    kind = "primitive" if t in CPP_PRIM else m.kind_of(t)
    if f.type.array:
        o = [f"{ind}{{\n{ind}    {('std::vector<' + cpp_base(m, t) + '>')} tmp;\n{ind}    for (size_t i = 0; i < {src}_len; i++) tmp.push_back({leaf_from_c(m, t, src + '[i]', ind)});\n{ind}    v.{f.name} = std::move(tmp);\n{ind}}}\n"]
        return "".join(o)
    if kind == "map":
        return f"{ind}{{\n{ind}    std::map<std::string, {CPP_PRIM[m.maps[t].value]}> tmp;\n{ind}    for (size_t i = 0; i < {src}.len; i++) tmp[{src}.items[i].key] = {src}.items[i].value;\n{ind}    v.{f.name} = std::move(tmp);\n{ind}}}\n"
    return f"{ind}v.{f.name} = {leaf_from_c(m, t, src, ind)};\n"
