"""Markdown reference emitter."""
from __future__ import annotations

from pathlib import Path

from model import Model


def emit(m: Model, out_dir: Path) -> None:
    o: list[str] = [f"# {m.protocol['description']} — protocol reference\n\n"]
    o.append(f"<!-- @generated by protocol/rrcgen from protocol/rrcloud.protocol.toml — do not edit -->\n\n")
    o.append(f"Definition v{m.protocol['idl_version']}, wire version {m.protocol['wire_version']}. Normative design: `docs/ARCHITECTURE.md`.\n\n")
    o.append("## Constants\n\n| Name | Type | Value | Meaning |\n|---|---|---|---|\n")
    for c in m.constants.values():
        o.append(f"| `{c.name}` | `{c.type}` | `{c.value}` | {c.doc} |\n")
    o.append("\n## Scalars\n\n| Name | Kind | Format | Meaning |\n|---|---|---|---|\n")
    for s in m.scalars.values():
        fmt = s.format + (f" (len {s.length})" if s.length else "") + (f", max {s.max_length} bytes" if s.max_length and not s.length else "")
        o.append(f"| `{s.name}` | {s.kind} | {fmt} | {s.doc} |\n")
    o.append("\n## Enums\n\n")
    for e in m.enums.values():
        o.append(f"### `{e.name}`\n\n{e.doc}\n\n| Value | Wire | Meaning |\n|---|---|---|\n")
        for v in e.values:
            o.append(f"| `{v.name}` | `\"{v.wire}\"` | {v.doc} |\n")
        o.append("\n")
    o.append("## Maps\n\n| Name | Key | Value | Zero components | Meaning |\n|---|---|---|---|---|\n")
    for mp in m.maps.values():
        o.append(f"| `{mp.name}` | `{mp.key}` | `{mp.value}` | {'dropped' if mp.drop_zero else 'kept'} | {mp.doc} |\n")
    o.append("\n## Records\n\nField order is the encoding order. *Required* fields must be present; *optional* fields are omitted when absent; *default* fields are filled in by decoders.\n\n")
    for r in m.records.values():
        o.append(f"### `{r.name}`\n\n{r.doc}\n\n")
        if r.version_field:
            o.append(f"Version gate: field `{r.version_field}` must be one of {r.supported_versions}; anything else is a fail-closed decode error.\n\n")
        if r.naming == "camel":
            o.append("Wire names are camelCase.\n\n")
        o.append("| Field | Wire name | Type | Presence | Meaning |\n|---|---|---|---|---|\n")
        for f in r.fields:
            pres = "optional" if f.optional else (f"default `{f.default!r}`" if f.has_default else "required")
            o.append(f"| `{f.name}` | `{f.wire_name(r.naming)}` | `{f.type}` | {pres} | {f.doc} |\n")
        o.append("\n")
    o.append("## Bucket keys\n\n| Name | Template | Meaning |\n|---|---|---|\n")
    for k in m.keys.values():
        o.append(f"| `{k.name}` | `{k.template}` | {k.doc} |\n")
    o.append("\n## Documents\n\n| Name | Where | Encoding | Content | Writer | Limits | Notes |\n|---|---|---|---|---|---|---|\n")
    for d in m.documents.values():
        v = d.data
        where = f"key `{v['key']}`" if "key" in v else f"HTTP `{v.get('http','')}` (auth: {v.get('auth','')})"
        content = v.get("record") or (f"header `{v.get('header')}`, rows {', '.join('`' + x + '`' for x in v.get('rows', []))}" if v.get("header") else "—")
        o.append(f"| `{d.name}` | {where} | {v.get('encoding','')} | {content} | {v.get('writer','')} | {', '.join('`' + l + '`' for l in v.get('limits', []))} | {v.get('doc','')} |\n")
    o.append("\n## S3 operations an implementation needs\n\n| Operation | Notes |\n|---|---|\n")
    for op in m.operations:
        o.append(f"| {op['name']} | {op.get('notes','')} |\n")
    (out_dir / "PROTOCOL.md").write_text("".join(o), encoding="utf-8")
