//! Interop: documents emitted by the ESP32 ingest-dock firmware
//! (`firmware/rrcloud-ingest`, host_tests/fixtures) must decode with THIS
//! crate's strict wire decoders — the same code every phone/desktop/worker
//! applies them with. The fixtures are regenerated by the firmware's host test
//! suite (`test_proto <gz> <fixtures-dir>`), so a drift in either codec fails
//! here rather than in a bucket.

use std::path::PathBuf;

use rrcloud_core::journal::{decode_segment, Kind, Op};
use rrcloud_core::keys::{classify_key, KeyClass};
use rrcloud_core::manifest::decode_manifest;
use rrcloud_core::publisher::DeviceEntry;

fn fixture(name: &str) -> Vec<u8> {
    let p = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../../firmware/rrcloud-ingest/host_tests/fixtures")
        .join(name);
    std::fs::read(&p).unwrap_or_else(|e| panic!("read {}: {e}", p.display()))
}

const DEVICE: &str = "0f6b2a1e-1111-4222-8333-944444444444";
const B3: &str = "6a0f8e2d3c4b5a69788796a5b4c3d2e1f0f1e2d3c4b5a69788796a5b4c3d2e1f";

#[test]
fn firmware_journal_segment_decodes_as_v1_put_originals() {
    let entries = decode_segment(&fixture("0000000000000001.v1.ndjson")).expect("segment decodes");
    assert_eq!(entries.len(), 2);
    let e = &entries[0];
    assert_eq!(e.v, 1);
    assert_eq!(e.seq, 1);
    assert_eq!(e.device.as_str(), DEVICE);
    assert_eq!(e.op, Op::Put);
    assert_eq!(e.kind, Kind::Original);
    assert_eq!(e.key, "library/2026/10/IMG_0042.NEF");
    assert_eq!(e.size, Some(48213));
    assert_eq!(e.blake3.as_ref().map(|h| h.as_str()), Some(B3));
    assert_eq!(e.content_id.as_ref().map(|c| c.as_str()), Some(B3));
    assert_eq!(e.mtime, Some(1769899000));
    assert_eq!(e.w, None);
    assert_eq!(e.h, None);
    assert_eq!(e.vv.get(&e.device), 1);
    assert_eq!(e.vv.len(), 1);
    // The key the firmware wrote classifies as a library original with the expected relkey.
    match classify_key(&e.key) {
        KeyClass::Original { relkey } => assert_eq!(relkey.as_str(), "2026/10/IMG_0042.NEF"),
        other => panic!("unexpected class {other:?}"),
    }
    // Second entry: no mtime, a key with spaces (template default), seq 2.
    let e2 = &entries[1];
    assert_eq!(e2.seq, 2);
    assert_eq!(e2.mtime, None);
    match classify_key(&e2.key) {
        KeyClass::Original { relkey } => {
            assert_eq!(
                relkey.as_str(),
                "Camera Import/NIKON Z f/2026/10/10/DSC_0002.NEF"
            )
        }
        other => panic!("unexpected class {other:?}"),
    }
}

#[test]
fn firmware_device_entry_decodes() {
    let d: DeviceEntry =
        serde_json::from_slice(&fixture("device.json")).expect("device entry decodes");
    assert_eq!(d.name, "Camera dock");
    assert_eq!(d.platform, "esp32");
    assert_eq!(d.created, 1769000000);
    assert_eq!(d.last_seen_server_ts, 1769900000);
    assert!(d.applied.is_empty());
    assert_eq!(d.proto.read, vec![1]);
    assert_eq!(d.proto.write, 1);
}

#[test]
fn firmware_manifest_gzip_decodes_with_the_strict_decoder() {
    let m = decode_manifest(&fixture("manifest.json.gz")).expect("manifest decodes");
    assert_eq!(m.header.proto, 1);
    assert_eq!(m.header.written_server_ts, 1769900000);
    let dev = rrcloud_core::clock::DeviceId::new(DEVICE).unwrap();
    assert_eq!(m.header.cursors.get(&dev), Some(&2));
    assert_eq!(m.rows.len(), 2);
    assert!(m.deleted.is_empty());
    let r = &m.rows[0];
    assert_eq!(r.key.as_str(), "2026/10/IMG_0042.NEF");
    assert_eq!(r.kind, Kind::Original);
    assert_eq!(r.size, 48213);
    assert_eq!(r.blake3.as_ref().map(|h| h.as_str()), Some(B3));
    assert_eq!(r.device.as_ref().map(|d| d.as_str()), Some(DEVICE));
    assert_eq!(r.content_id.as_ref().map(|c| c.as_str()), Some(B3));
    assert_eq!(r.mtime, Some(1769899000));
    assert_eq!(r.ts, Some(1769900000));
    assert_eq!(r.vv.get(&dev), 1);
    assert_eq!(
        m.rows[1].key.as_str(),
        "Camera Import/NIKON Z f/2026/10/10/DSC_0002.NEF"
    );
    assert_eq!(m.rows[1].mtime, None);
}
